--------------------------------------------------------
-- 1. DROP EXISTING TABLES (Enables easy re-runs)
--------------------------------------------------------
BEGIN
 FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN
 ('ADMIN_INFO', 'ANNOUNCEMENT', 'APPLICATION', 'CATEGORY', 'CLUBS',
 'CLUB_CATEGORY', 'EVENTS', 'STUDENT_INFO', 'USERS', 'USERS_CLUB'))
 LOOP
 EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS';
 END LOOP;
END;
/
--------------------------------------------------------
-- 2. CREATE TABLES (Aligned with 3NF Relational Schema)
--------------------------------------------------------
CREATE TABLE "USERS" (
 "USER_ID" NUMBER(*,0),
 "USER_NAME" VARCHAR2(100 BYTE),
 "USER_PASSWORD" VARCHAR2(50 BYTE),
 "USER_EMAIL" VARCHAR2(100 BYTE),
 "IS_ACTIVE" NUMBER(1), -- Changed from BOOLEAN to NUMBER(1) for compatibility
 "USER_TYPE" VARCHAR2(20 BYTE)
) TABLESPACE "USERS";
CREATE TABLE "STUDENT_INFO" (
 "USER_ID" NUMBER(*,0),
 "STUDENT_NUMBER" NUMBER(*,0),
 "STUDENT_PROGRAM" VARCHAR2(50 BYTE),
 "STUDENT_FACULTY" VARCHAR2(50 BYTE),
 "STUDENT_SEMESTER" NUMBER(*,0)
) TABLESPACE "USERS";
CREATE TABLE "ADMIN_INFO" (
 "USER_ID" NUMBER(*,0),
 "ADMIN_POSITION" VARCHAR2(20 BYTE),
 "ADMIN_DEPARTMENT" VARCHAR2(50 BYTE)
) TABLESPACE "USERS";
CREATE TABLE "CLUBS" (
 "CLUB_ID" NUMBER(*,0),
 "CLUB_NAME" VARCHAR2(100 BYTE),
 "CLUB_MISSION" VARCHAR2(999 BYTE),
 "CLUB_VISION" VARCHAR2(999 BYTE),
 "CLUB_EMAIL" VARCHAR2(100 BYTE),
 "CLUB_PHONE" VARCHAR2(20 BYTE),
 "ADVISOR_NAME" VARCHAR2(100 BYTE),
 "ADVISOR_EMAIL" VARCHAR2(50 BYTE),
 "ADVISOR_PHONE" VARCHAR2(20 BYTE)
) TABLESPACE "USERS";
CREATE TABLE "CATEGORY" (
 "CATEGORY_ID" NUMBER(*,0),
 "CATEGORY_NAME" VARCHAR2(100 BYTE)
) TABLESPACE "USERS";
CREATE TABLE "CLUB_CATEGORY" (
 "CLUB_CAT_ID" NUMBER(*,0),
 "CLUB_ID" NUMBER(*,0),
 "CATEGORY_ID" NUMBER(*,0)
) TABLESPACE "USERS";
CREATE TABLE "EVENTS" (
 "EVENT_ID" NUMBER(*,0),
 "EVENT_NAME" VARCHAR2(100 BYTE),
 "EVENT_DESC" VARCHAR2(999 BYTE),
 "EVENT_TYPE" VARCHAR2(50 BYTE),
 "EVENT_DATETIME" DATE,
 "CLUB_ID" NUMBER(*,0)
) TABLESPACE "USERS";
CREATE TABLE "ANNOUNCEMENT" (
 "ANNC_ID" NUMBER(*,0),
 "ANNC_TITLE" VARCHAR2(100 BYTE),
 "ANNC_CONTENT" VARCHAR2(999 BYTE),
 "ANNC_TYPE" VARCHAR2(50 BYTE),
 "ANNC_DATE" DATE,
 "CLUB_ID" NUMBER(*,0)
) TABLESPACE "USERS";
CREATE TABLE "APPLICATION" (
 "APPLICATION_ID" NUMBER(*,0),
 "APPLICATION_STATUS" VARCHAR2(10 BYTE),
 "USER_ID" NUMBER(*,0),
 "CLUB_ID" NUMBER(*,0)
) TABLESPACE "USERS";
CREATE TABLE "USERS_CLUB" (
 "USER_CLUB_ID" NUMBER(*,0),
 "USER_ID" NUMBER(*,0),
 "CLUB_ID" NUMBER(*,0)
) TABLESPACE "USERS";
--------------------------------------------------------
-- 3. ADD PRIMARY KEYS
--------------------------------------------------------
ALTER TABLE "USERS" ADD PRIMARY KEY ("USER_ID");
ALTER TABLE "STUDENT_INFO" ADD PRIMARY KEY ("USER_ID");
ALTER TABLE "ADMIN_INFO" ADD PRIMARY KEY ("USER_ID");
ALTER TABLE "CLUBS" ADD PRIMARY KEY ("CLUB_ID");
ALTER TABLE "CATEGORY" ADD PRIMARY KEY ("CATEGORY_ID");
ALTER TABLE "CLUB_CATEGORY" ADD PRIMARY KEY ("CLUB_CAT_ID");
ALTER TABLE "EVENTS" ADD PRIMARY KEY ("EVENT_ID");
ALTER TABLE "ANNOUNCEMENT" ADD PRIMARY KEY ("ANNC_ID");
ALTER TABLE "APPLICATION" ADD PRIMARY KEY ("APPLICATION_ID");
ALTER TABLE "USERS_CLUB" ADD PRIMARY KEY ("USER_CLUB_ID");
--------------------------------------------------------
-- 4. ADD FOREIGN KEYS (Ref Constraints)
--------------------------------------------------------
ALTER TABLE "STUDENT_INFO" ADD CONSTRAINT "FK_STUDENT_USER" FOREIGN KEY
("USER_ID") REFERENCES "USERS" ("USER_ID");
ALTER TABLE "ADMIN_INFO" ADD CONSTRAINT "FK_ADMIN_USER" FOREIGN KEY
("USER_ID") REFERENCES "USERS" ("USER_ID");
ALTER TABLE "ANNOUNCEMENT" ADD CONSTRAINT "FK_ANNOUNCEMENT_CLUB"
FOREIGN KEY ("CLUB_ID") REFERENCES "CLUBS" ("CLUB_ID");
ALTER TABLE "APPLICATION" ADD CONSTRAINT "FK_APP_USER" FOREIGN KEY ("USER_ID")
REFERENCES "USERS" ("USER_ID");
ALTER TABLE "APPLICATION" ADD CONSTRAINT "FK_APP_CLUB" FOREIGN KEY ("CLUB_ID")
REFERENCES "CLUBS" ("CLUB_ID");
ALTER TABLE "CLUB_CATEGORY" ADD CONSTRAINT "FK_CC_CLUB" FOREIGN KEY
("CLUB_ID") REFERENCES "CLUBS" ("CLUB_ID");
ALTER TABLE "CLUB_CATEGORY" ADD CONSTRAINT "FK_CC_CATEGORY" FOREIGN KEY
("CATEGORY_ID") REFERENCES "CATEGORY" ("CATEGORY_ID");
ALTER TABLE "EVENTS" ADD CONSTRAINT "FK_EVENT_CLUB" FOREIGN KEY ("CLUB_ID")
REFERENCES "CLUBS" ("CLUB_ID");
ALTER TABLE "USERS_CLUB" ADD CONSTRAINT "FK_UC_USER" FOREIGN KEY ("USER_ID")
REFERENCES "USERS" ("USER_ID");
ALTER TABLE "USERS_CLUB" ADD CONSTRAINT "FK_UC_CLUB" FOREIGN KEY ("CLUB_ID")
REFERENCES "CLUBS" ("CLUB_ID");
--------------------------------------------------------
-- 1. INSERT CATEGORIES
--------------------------------------------------------
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'Technology');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'Sports');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES (3, 'Academic');
--------------------------------------------------------
-- 2. INSERT CLUBS
--------------------------------------------------------
INSERT INTO CLUBS (CLUB_ID, CLUB_NAME, CLUB_MISSION, CLUB_VISION, CLUB_EMAIL,
CLUB_PHONE, ADVISOR_NAME, ADVISOR_EMAIL, ADVISOR_PHONE)
VALUES (101, 'Computer Science Society', 'Empowering students with tech skills', 'Leading
tech hub in UiTM', 'css@uitm.edu.my', '03-5544001', 'Dr. Ahmad', 'ahmad@uitm.edu.my',
'012-3456789');
INSERT INTO CLUBS (CLUB_ID, CLUB_NAME, CLUB_MISSION, CLUB_VISION, CLUB_EMAIL,
CLUB_PHONE, ADVISOR_NAME, ADVISOR_EMAIL, ADVISOR_PHONE)
VALUES (102, 'Badminton Club', 'Promoting healthy lifestyle', 'Champions on court',
'badminton@uitm.edu.my', '03-5544002', 'Coach Rizal', 'rizal@uitm.edu.my', '019-
8765432');
--------------------------------------------------------
-- 3. INSERT USERS (Matches names in your PDF)
--------------------------------------------------------
-- Student 1: Ibtisam [cite: 1, 59]
INSERT INTO USERS (USER_ID, USER_NAME, USER_PASSWORD, USER_EMAIL, IS_ACTIVE,
USER_TYPE)
VALUES (1, 'IBTISAM BINTI ASRUL HAFIZ', 'pass123', '2025380867@student.uitm.edu.my',
1, 'student');
-- Student 2: Nur Atiqah [cite: 1, 38]
INSERT INTO USERS (USER_ID, USER_NAME, USER_PASSWORD, USER_EMAIL, IS_ACTIVE,
USER_TYPE)
VALUES (2, 'NUR ATIQAH ZULAIKA BINTI ISMAIL', 'pass456',
'2025111081@student.uitm.edu.my', 1, 'student');
-- Admin User [cite: 17, 31]
INSERT INTO USERS (USER_ID, USER_NAME, USER_PASSWORD, USER_EMAIL, IS_ACTIVE,
USER_TYPE)
VALUES (99, 'System Administrator', 'admin123', 'admin@uitm.edu.my', 1, 'admin');
--------------------------------------------------------
-- 4. INSERT STUDENT_INFO [cite: 163-173, 257]
--------------------------------------------------------
INSERT INTO STUDENT_INFO (USER_ID, STUDENT_NUMBER, STUDENT_PROGRAM,
STUDENT_FACULTY, STUDENT_SEMESTER)
VALUES (1, 2025380867, 'CS230', 'FSKM', 3);
INSERT INTO STUDENT_INFO (USER_ID, STUDENT_NUMBER, STUDENT_PROGRAM,
STUDENT_FACULTY, STUDENT_SEMESTER)
VALUES (2, 2025111081, 'CS230', 'FSKM', 4);
--------------------------------------------------------
-- 5. INSERT EVENTS & ANNOUNCEMENTS [cite: 124-133, 264]
--------------------------------------------------------
INSERT INTO EVENTS (EVENT_ID, EVENT_NAME, EVENT_DESC, EVENT_TYPE,
EVENT_DATETIME, CLUB_ID)
VALUES (501, 'Web Dev Workshop', 'Learn HTML and CSS', 'Workshop', TO_DATE('2026-
01-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 101);
INSERT INTO ANNOUNCEMENT (ANNC_ID, ANNC_TITLE, ANNC_CONTENT, ANNC_TYPE,
ANNC_DATE, CLUB_ID)
VALUES (601, 'Welcome Members', 'Welcome to the new semester!', 'General', SYSDATE,
101);
--------------------------------------------------------
-- 6. INSERT APPLICATIONS (Sample Pending) [cite: 204-210, 261]
--------------------------------------------------------
INSERT INTO APPLICATION (APPLICATION_ID, APPLICATION_STATUS, USER_ID, CLUB_ID)
VALUES (701, 'Pending', 1, 101);
COMMIT; -- Save all changes
SELECT u.USER_NAME, s.STUDENT_NUMBER, s.STUDENT_PROGRAM,
s.STUDENT_FACULTY
FROM USERS u
JOIN STUDENT_INFO s ON u.USER_ID = s.USER_ID;
SELECT c.CLUB_NAME, cat.CATEGORY_NAME
FROM CLUBS c
JOIN CLUB_CATEGORY cc ON c.CLUB_ID = cc.CLUB_ID
JOIN CATEGORY cat ON cc.CATEGORY_ID = cat.CATEGORY_ID
WHERE cat.CATEGORY_NAME = 'Technology';
SELECT EVENT_NAME, EVENT_TYPE, EVENT_DATETIME
FROM EVENTS
WHERE CLUB_ID = 101;
SELECT u.USER_NAME, c.CLUB_NAME, a.APPLICATION_STATUS
FROM APPLICATION a
JOIN USERS u ON a.USER_ID = u.USER_ID
JOIN CLUBS c ON a.CLUB_ID = c.CLUB_ID
WHERE a.APPLICATION_STATUS = 'Pending';
-- Run this in SQL Developer to allow automatic IDs starting at 1
-- Part ni mungkin bertambah
CREATE SEQUENCE user_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE club_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE club_cat_seq START WITH 100 INCREMENT BY 1;
-- added at 17/1/2026
CREATE SEQUENCE application_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE event_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE announcement_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE admin_info_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE student_info_seq START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE user_club_seq START WITH 100 INCREMENT BY 1;

SELECT USER_EMAIL, USER_PASSWORD, USER_TYPE FROM USERS ;